# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MutualFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amfisymbol', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundNAV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('nav', models.DecimalField(decimal_places=6, max_digits=20)),
                ('mf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav', to='navserver.MutualFund')),
            ],
        ),
    ]
