# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 07:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('navserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutualfundnav',
            name='mf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav', to='navserver.Mutualfund'),
        ),
    ]
