# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navserver', '0004_auto_20160826_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutualfund',
            name='mfname',
            field=models.CharField(default='Unnamed MF', max_length=300),
        ),
    ]
